version: 2.1

executors:
  python:
    parameters:
      image_tag:
        type: string
        default: python:3.7
    docker:
      - image: circleci/<< parameters.image_tag >>

commands:
  installation:
    steps:
      - checkout
      - run:
          name: Installation
          command: |
            python setup.py sdist
            PACKAGE=$(python setup.py --fullname)
            tar -zxvf dist/${PACKAGE}.tar.gz
            mv ${PACKAGE} package
            virtualenv python -q
            source python/bin/activate
            pip install -e package --progress-bar off
            pip install -r package/test-requirements.txt --progress-bar off

jobs:
  Lint Tests:
    parameters:
      image_tag:
        type: string
        default: python:3.7
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: Lint Tests
          command: |
            source python/bin/activate
            make -C package lint --makefile ../Makefile

  Unit Tests:
    parameters:
      image_tag:
        type: string
        default: python:3.7
      codecov:
        type: boolean
        default: false
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: Unit Tests
          command: |
            source python/bin/activate
            pytest autonormalize/
      - when:
          condition: << parameters.codecov >>
          steps:
            - run:
                name: Code Coverage
                command: |
                  source python/bin/activate
                  cd package
                  codecov

  Entry Point Test:
    parameters:
      image_tag:
        type: string
        default: python:3.7
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: Entry Point Test
          command: |
            source python/bin/activate
            make -C package entry-point-test --makefile ../Makefile

workflows:
  version: 2
  Integration Tests:
    jobs:
      - Lint Tests:
          name: Py35 - Lint Tests
          image_tag: python:3.5
      - Lint Tests:
          name: Py36 - Lint Tests
          image_tag: python:3.6
      - Lint Tests:
          name: Py37 - Lint Tests
          image_tag: python:3.7
      - Unit Tests:
          name: Py35 - Unit Tests
          image_tag: python:3.5
      - Unit Tests:
          name: Py36 - Unit Tests
          image_tag: python:3.6
      - Unit Tests:
          name: Py37 - Unit Tests
          image_tag: python:3.7
          codecov: true
      - Entry Point Test:
          name: Py35 - Entry Point Test
          image_tag: python:3.5
      - Entry Point Test:
          name: Py36 - Entry Point Test
          image_tag: python:3.6
      - Entry Point Test:
          name: Py37 - Entry Point Test
          image_tag: python:3.7
